ifndef::manversion[:manversion: 0.0.0]

= netstate(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: NETSTATE
:mansource: NETSTATE


== Name

netstate - run hooks automatically on network state change for systems using systemd-networkd


== Synopsis

*netstate* {_query_, _-Q_}

*netstate* {_watch_, _-W_}


== Description

*netstate* runs in the background, executing hooks when network connectivity state changes (goes online or offline).
It is designed to be set up once, for example as a _systemd.service(5)_.


== Commands

*query*::
Prints the current network state (`online` or `offline`).

*watch*::
Runs the *netstate* service and executes hooks on network connectivity state change.
Hooks are executable files in _$XDG_DATA_HOME/netstate/_.
If _$XDG_DATA_HOME_ is unset, it defaults to _$HOME/.local/share_.
Hooks are executed with a single argument, the new state (`online` or `offline`).

== Sample hooks

=== Notifications

[source,bash]
----
notify-send -a netstate "Network state: $1"
----

=== Waybar module update

[source,bash]
----
pkill # TODO...
----



== See also

_darkman(1)_
