ifndef::manversion[:manversion: 0.0.0]

= netstate(1)
Matthieu Monsch
v{manversion}
:doctype: manpage
:manmanual: NETSTATE
:mansource: NETSTATE


== Name

netstate - run hooks on changes to network state for systems using systemd-networkd


== Synopsis

*netstate* {_query_, _-Q_}

*netstate* {_watch_, _-W_}


== Description

*netstate* runs in the background, executing hooks when network connectivity state changes (goes online or offline).
It is designed to be set up once, for example as a user _systemd.service(5)_.


== Commands

*query*::
Prints the current network state (`online` or `offline`).

*watch*::
Runs the *netstate* service and executes hooks on network connectivity state change.
Hooks are executable files in `$XDG_DATA_HOME/netstate/hooks.d`.
If `$XDG_DATA_HOME` is unset, it defaults to `$HOME/.local/share`.
Hooks are executed in lexicographic order with a single argument, the new state (`online` or `offline`).
If `$RUNTIME_DIRECTORY` is set, it will be used as working directory when running scripts.

== Sample hooks

=== Notifications

Basic script:

[source,bash]
----
notify-send -a netstate "Network state: $1"
----

Fancier example, reusing the same notification:

[source,bash]
----
# Notification ID path, used to reuse notifications.
nid_path=notify_id

main() { # STATE
	local state="${1:-}" args
	case "$state" in
		online) args=(Connected) ;;
		offline) args=(-u critical Disconnected 'Lost network connection.') ;;
		*) fail "unexpected state: $state" ;;
	esac

	local nid=0
	if [[ -e $nid_path ]]; then
		nid="$(cat "$nid_path")"
	fi
	if command -v notify-send >/dev/null; then
		notify-send -a netstate -t 7500 -r "$nid" -p "${args[@]}" >"$nid_path"
	fi
}

fail() { # MSG
	printf 'error: %s\n' "$1" >&2 && exit 1
}

main "$@"
----

=== Waybar module update

Custom modules with a signal defined can be reloaded via a hook.
For example, assuming signal 8:

[source,bash]
----
pkill -RTMIN+8 waybar
----


== See also

_darkman(1)_
_networkd-dispatcher(8)_
_systemd-networkd(8)_
